--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-11-2018   
--------------------------------------------------------
DROP TABLE "TAKEMEAL"."TBL_REPLY" cascade constraints;
DROP TABLE "TAKEMEAL"."TBL_BOARD" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence TBL_REPLY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAKEMEAL"."TBL_REPLY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_REPLY
--------------------------------------------------------

  CREATE TABLE "TAKEMEAL"."TBL_REPLY" 
   (	"RNO" NUMBER, 
	"BNO" NUMBER, 
	"REPLYTEXT" VARCHAR2(1000 BYTE), 
	"REPLYER" VARCHAR2(100 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"UPDATEDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_BOARD
--------------------------------------------------------

  CREATE TABLE "TAKEMEAL"."TBL_BOARD" 
   (	"BNO" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"WRITER" VARCHAR2(200 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"VIEWCNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TAKEMEAL.TBL_REPLY
SET DEFINE OFF;
Insert into TAKEMEAL.TBL_REPLY (RNO,BNO,REPLYTEXT,REPLYER,REGDATE,UPDATEDATE) values (1,200,'asdasdasd','테스트',to_date('18/06/11 04:35','RR/MM/DD HH24:MI'),to_date('18/06/11 04:35','RR/MM/DD HH24:MI'));
Insert into TAKEMEAL.TBL_REPLY (RNO,BNO,REPLYTEXT,REPLYER,REGDATE,UPDATEDATE) values (2,200,'45645646456','45646456',to_date('18/06/11 06:15','RR/MM/DD HH24:MI'),to_date('18/06/11 06:15','RR/MM/DD HH24:MI'));
Insert into TAKEMEAL.TBL_REPLY (RNO,BNO,REPLYTEXT,REPLYER,REGDATE,UPDATEDATE) values (3,200,'ㅁㅇㅁㄴㅇㅁㄴㅇ','ㅁㅇㄴㅇㄴㅁㄴㅇㄴ',to_date('18/06/11 06:15','RR/MM/DD HH24:MI'),to_date('18/06/11 06:15','RR/MM/DD HH24:MI'));
--------------------------------------------------------
--  DDL for Index TBL_REPLY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAKEMEAL"."TBL_REPLY_PK" ON "TAKEMEAL"."TBL_REPLY" ("RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TBL_REPLY
--------------------------------------------------------

  ALTER TABLE "TAKEMEAL"."TBL_REPLY" ADD CONSTRAINT "TBL_REPLY_PK" PRIMARY KEY ("RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TAKEMEAL"."TBL_REPLY" MODIFY ("UPDATEDATE" NOT NULL ENABLE);
  ALTER TABLE "TAKEMEAL"."TBL_REPLY" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "TAKEMEAL"."TBL_REPLY" MODIFY ("RNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_REPLY
--------------------------------------------------------

  ALTER TABLE "TAKEMEAL"."TBL_REPLY" ADD CONSTRAINT "FK_BOARD" FOREIGN KEY ("BNO")
	  REFERENCES "TAKEMEAL"."TBL_BOARD" ("BNO") ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_REPLY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TAKEMEAL"."TBL_REPLY_TRG" 
BEFORE INSERT ON TBL_REPLY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.RNO IS NULL THEN
      SELECT TBL_REPLY_SEQ.NEXTVAL INTO :NEW.RNO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TAKEMEAL"."TBL_REPLY_TRG" ENABLE;
