--------------------------------------------------------
--  ÆÄÀÏÀÌ »ý¼ºµÊ - ¿ù¿äÀÏ-6¿ù-18-2018   
--------------------------------------------------------
DROP TABLE "TAKEMEAL"."ALL_FOOD" cascade constraints;
DROP TABLE "TAKEMEAL"."FOOD" cascade constraints;
DROP TABLE "TAKEMEAL"."MEMBER" cascade constraints;
--------------------------------------------------------
--  DDL for Table ALL_FOOD
--------------------------------------------------------

  CREATE TABLE "TAKEMEAL"."ALL_FOOD" 
   (	"NO" NUMBER(3,0), 
	"CLASS_CODE" VARCHAR2(2 BYTE), 
	"FOOD_CODE" NUMBER(3,0), 
	"FOOD_NAME" VARCHAR2(30 BYTE), 
	"COOL_SYS" VARCHAR2(10 BYTE), 
	"EXPIRY_DATE" DATE, 
	"FOOD_COUNT" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TAKEMEAL"."ALL_FOOD"."NO" IS 'È¸¿ø¹øÈ£';
   COMMENT ON COLUMN "TAKEMEAL"."ALL_FOOD"."CLASS_CODE" IS '½ÄÇ°ÄÚµå';
   COMMENT ON COLUMN "TAKEMEAL"."ALL_FOOD"."FOOD_CODE" IS 'Àç·áÄÚµå';
   COMMENT ON COLUMN "TAKEMEAL"."ALL_FOOD"."FOOD_NAME" IS 'Àç·áÀÌ¸§';
   COMMENT ON COLUMN "TAKEMEAL"."ALL_FOOD"."COOL_SYS" IS 'º¸°üÇüÅÂ';
   COMMENT ON COLUMN "TAKEMEAL"."ALL_FOOD"."EXPIRY_DATE" IS 'À¯Åë±âÇÑ';
   COMMENT ON COLUMN "TAKEMEAL"."ALL_FOOD"."FOOD_COUNT" IS '¼ö·®';
--------------------------------------------------------
--  DDL for Table FOOD
--------------------------------------------------------

  CREATE TABLE "TAKEMEAL"."FOOD" 
   (	"CLASS_CODE" VARCHAR2(2 BYTE), 
	"CLASS_NAME" VARCHAR2(30 BYTE), 
	"TABLE_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TAKEMEAL"."FOOD"."CLASS_CODE" IS '½ÄÇ°ÄÚµå';
   COMMENT ON COLUMN "TAKEMEAL"."FOOD"."CLASS_NAME" IS '½ÄÇ°ÀÌ¸§';
   COMMENT ON COLUMN "TAKEMEAL"."FOOD"."TABLE_CODE" IS 'Å×ÀÌºíºÐ·ù';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "TAKEMEAL"."MEMBER" 
   (	"NO" NUMBER, 
	"USERID" VARCHAR2(200 BYTE), 
	"PASSWORD" VARCHAR2(200 BYTE), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"TYPE" NUMBER, 
	"PHONE" VARCHAR2(150 BYTE), 
	"BLOG" VARCHAR2(250 BYTE), 
	"REG_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TAKEMEAL.ALL_FOOD
SET DEFINE OFF;
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'ME',101,'¼Òµî½É','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'ME',102,'¼Ò¾È½É','³Ãµ¿',null,4);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'ME',103,'¼Ò°¥ºñ','³ÃÀå',null,4);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'ME',201,'»ï°ã»ì','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'ME',202,'¸ñ»ì','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'ME',203,'µÅÁö°¥ºñ','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'ME',301,'´ßÇÑ¸¶¸®','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'ME',302,'´ß°¡½¿»ì','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'ME',303,'´ß¹ß','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'ME',304,'´ß°¥ºñ','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',101,'¹é¹Ì','½Ç¿Â',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',102,'Èæ¹Ì','½Ç¿Â',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',103,'Çö¹Ì','½Ç¿Â',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',201,'¿Á¼ö¼ö','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',202,'°­³¶Äá','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',203,'°ËÀºÄá','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',204,'¿ÏµÎÄá','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',301,'¹Ð°¡·ç','½Ç¿Â',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',302,'½Ò°¡·ç','½Ç¿Â',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',303,'Æ¢±è°¡·ç','½Ç¿Â',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',304,'»§°¡·ç','½Ç¿Â',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',401,'½Ä»§','½Ç¿Â',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',402,'¹Ù°ÔÆ®»§','½Ç¿Â',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',403,'º£ÀÌ±Û','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',501,'¶±±¹¶±','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'CR',502,'Á¶·©ÀÌ¶±','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'EG',101,'°è¶õ','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'EG',102,'¸ÞÃß¸®¾Ë','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'EG',103,'¿À¸®¾Ë','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'FS',101,'°íµî¾î','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'FS',102,'µ¿ÅÂ','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'FS',103,'»ïÄ¡','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'FS',104,'°¥Ä¡','³ÃÀå',null,2);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'FS',201,'¹ÙÁö¶ô','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'FS',202,'¸ð½ÃÁ¶°³','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'FS',203,'²¿¸·','³Ãµ¿',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'FS',301,'¸¶¸¥¹Ì¿ª','½Ç¿Â',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'FS',302,'¸¶¸¥´Ù½Ã¸¶','½Ç¿Â',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'MK',101,'¿ìÀ¯','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'MK',102,'¿ä°ÅÆ®','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'MK',201,'Ã¼´ÙÄ¡Áî','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'MK',202,'¸®ÄÚÅ¸Ä¡Áî','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'VT',101,'²É»óÃß','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'VT',102,'Àû»óÃß','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'VT',103,'¾çÆÄ','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'VT',104,'¾ç¹èÃß','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'VT',105,'´ëÆÄ','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'VT',106,'ÂÊÆÄ','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'VT',107,'´ç±Ù','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'VT',108,'¸¶´Ã','³ÃÀå',null,0);
Insert into TAKEMEAL.ALL_FOOD (NO,CLASS_CODE,FOOD_CODE,FOOD_NAME,COOL_SYS,EXPIRY_DATE,FOOD_COUNT) values (1,'VT',109,'»ý°­','³ÃÀå',null,0);
--------------------------------------------------------
--  Constraints for Table ALL_FOOD
--------------------------------------------------------

  ALTER TABLE "TAKEMEAL"."ALL_FOOD" MODIFY ("FOOD_COUNT" NOT NULL ENABLE);
  ALTER TABLE "TAKEMEAL"."ALL_FOOD" MODIFY ("FOOD_CODE" NOT NULL ENABLE);
  ALTER TABLE "TAKEMEAL"."ALL_FOOD" MODIFY ("COOL_SYS" NOT NULL ENABLE);
  ALTER TABLE "TAKEMEAL"."ALL_FOOD" MODIFY ("FOOD_NAME" NOT NULL ENABLE);
  ALTER TABLE "TAKEMEAL"."ALL_FOOD" MODIFY ("CLASS_CODE" NOT NULL ENABLE);
  ALTER TABLE "TAKEMEAL"."ALL_FOOD" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ALL_FOOD
--------------------------------------------------------

  ALTER TABLE "TAKEMEAL"."ALL_FOOD" ADD CONSTRAINT "ALL_FOOD_FK1" FOREIGN KEY ("CLASS_CODE")
	  REFERENCES "TAKEMEAL"."FOOD" ("CLASS_CODE") ENABLE;
  ALTER TABLE "TAKEMEAL"."ALL_FOOD" ADD CONSTRAINT "ALL_FOOD_FK2" FOREIGN KEY ("NO")
	  REFERENCES "TAKEMEAL"."MEMBER" ("NO") ENABLE;
